chore(ci): run tasks on agents

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -77,40 +77,39 @@ jobs:
       - name: Set up dependencies
         uses: ./.github/actions/setup
 
-      - name: Start Nx Cloud DTE
-        # The --agent-count parameter must match the number of strategies run by the dte_agents job
-        run: yarn nx-cloud start-ci-run --agent-count=4
+      - name: Initialize the Nx Cloud distributed CI run
+        run: yarn nx-cloud start-ci-run
 
-      - name: Check formatting
-        env:
-          # DTE is disabled to run this step on the DTE coordinator while the agents are set up
-          NX_CLOUD_DISTRIBUTED_EXECUTION: false
-          NX_DISTRIBUTED_TASK_EXECUTION: false
-        run: yarn nx format:check
+      - name: Run commands in parallel
+        run: |
+          pids=()
+          # list of commands to be run on main has env flag NX_CLOUD_DISTRIBUTED_EXECUTION set to false
+          NX_CLOUD_DISTRIBUTED_EXECUTION=false yarn nx-cloud record -- yarn nx format:check & pids+=($!)
 
-      # Distribution strategy for 2 vCPUs per hosted runner (GitHub Free):
-      #
+          # list of commands to be run on agents
+          yarn nx affected -t lint --parallel=3 &
+          pids+=($!)
 
-      # lint: 3 tasks assigned at a time, 1 task per vCPU
-      - name: Run Affected lint
-        run: yarn nx affected:lint --parallel=3 --quiet
+          yarn nx affected -t test --parallel=3 &
+          pids+=($!)
 
-      # test: 3 tasks assigned at a time, 1 task per vCPU
-      - name: Run Affected test
-        id: test
-        run: yarn nx affected:test --parallel=3 --ci --code-coverage
+          yarn nx affected -t build --parallel=3 &
+          pids+=($!)
 
-      # build: 2 tasks assigned at a time, 1 task per vCPU
-      - name: Run Affected build
-        run: yarn nx affected:build --exclude=docs --parallel=2
+          yarn nx affected -t e2e --parallel=1 &
+          pids+=($!)
 
-      # e2e: 1 task assigned at a time, 1 task per vCPU
-      - name: Run Affected e2e
-        run: yarn nx affected:e2e --parallel=1
+          yarn nx affected -t component-test --parallel=1 &
+          pids+=($!)
 
-      # component tests: 1 task assigned at a time, 1 task per vCPU
-      - name: Run Affected component tests
-        run: yarn nx affected -t component-test --parallel=1
+          # run all commands in parallel and bail if one of them fails
+          for pid in ${pids[*]}; do
+            if ! wait $pid; then
+              exit 1
+            fi
+          done
+
+          exit 0
 
       - name: Stop Nx Cloud DTE agents
         if: ${{ always() }}
